[package]
name = "dovetail"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.37"
colored = "3.0.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tempfile = "3.19.1"
