name: dovetail
base: core24
version: '0.1'
summary:   Dovetail is a project-agnostic user-extensible workflow manager
description: |
  Manage workflows, environments, packaging, releases, deployment, and distribution centrally
grade: devel
confinement: classic

apps:
  dovetail:
    command: bin/dovetail

parts:
  dovetail:
    plugin: rust
    source: .
    build-environment:
      - RUSTFLAGS: >
          -C link-args=-Wl,-dynamic-linker=/snap/core24/current/lib64/ld-linux-x86-64.so.2
          -C link-args=-Wl,-rpath=/snap/core24/current/lib/x86_64-linux-gnu